// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrXDWoncCkNY41HaegoAfgqopoMoHEzcI',
    appId: '1:947277043703:web:98bea74d3a08350e8d80f2',
    messagingSenderId: '947277043703',
    projectId: 'codeflow-1f2c7',
    authDomain: 'codeflow-1f2c7.firebaseapp.com',
    storageBucket: 'codeflow-1f2c7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnDac-bQgpi7SzZe2Zh9rXpATDayeCbBg',
    appId: '1:947277043703:android:096ca36ab80227c58d80f2',
    messagingSenderId: '947277043703',
    projectId: 'codeflow-1f2c7',
    storageBucket: 'codeflow-1f2c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjZTb3Hi5cknmyV2wdRKnKy5OhcO__l50',
    appId: '1:947277043703:ios:e3349effec116f868d80f2',
    messagingSenderId: '947277043703',
    projectId: 'codeflow-1f2c7',
    storageBucket: 'codeflow-1f2c7.firebasestorage.app',
    iosBundleId: 'com.example.codeflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjZTb3Hi5cknmyV2wdRKnKy5OhcO__l50',
    appId: '1:947277043703:ios:e3349effec116f868d80f2',
    messagingSenderId: '947277043703',
    projectId: 'codeflow-1f2c7',
    storageBucket: 'codeflow-1f2c7.firebasestorage.app',
    iosBundleId: 'com.example.codeflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrXDWoncCkNY41HaegoAfgqopoMoHEzcI',
    appId: '1:947277043703:web:fbb04c60ac1f02f38d80f2',
    messagingSenderId: '947277043703',
    projectId: 'codeflow-1f2c7',
    authDomain: 'codeflow-1f2c7.firebaseapp.com',
    storageBucket: 'codeflow-1f2c7.firebasestorage.app',
  );
}
